# Cargo configuration for development and release builds

[build]
# Use all available CPU cores for compilation
jobs = 8

[target.x86_64-apple-darwin]
# macOS Intel
rustflags = ["-C", "link-arg=-s"]

[target.aarch64-apple-darwin]
# macOS Apple Silicon
rustflags = ["-C", "link-arg=-s"]

[target.x86_64-unknown-linux-gnu]
# Linux x86_64
rustflags = ["-C", "link-arg=-s"]

[target.x86_64-pc-windows-msvc]
# Windows
rustflags = ["-C", "link-arg=/SUBSYSTEM:CONSOLE"]

# Alias for quick development
[alias]
dev = "run --"
build-release = "build --release"
install-local = "install --path ."
